support python3

diff --git a/var/lib/dpkg/info/libc6:armhf.postinst b/var/lib/dpkg/info/libc6:armhf.postinst
--- a/var/lib/dpkg/info/libc6:armhf.postinst
+++ b/var/lib/dpkg/info/libc6:armhf.postinst
@@ -5,15 +5,6 @@ export LC_ALL=C
 type=$1
 preversion=$2
 
-package_name()
-{
-    if dpkg --assert-multi-arch 2>/dev/null; then
-        echo libc6:${DPKG_MAINTSCRIPT_ARCH}
-    else
-        echo libc6
-    fi
-}
-
 # element() is a helper function for file-rc:
 element() {
     local element list IFS
@@ -70,21 +61,11 @@ checkpkgver () {
 
 if [ "$type" = "configure" ]
 then
-    # Add support for /etc/ld.so.conf.d
-    if [ -e /etc/ld.so.conf ]; then
-        [ -z "$(tail -n 1 /etc/ld.so.conf)" ] || echo >> /etc/ld.so.conf
-    else
-        touch /etc/ld.so.conf
-    fi
-    if ! grep -q '^include /etc/ld.so.conf.d/.*\.conf$' /etc/ld.so.conf ; then
-        echo 'include /etc/ld.so.conf.d/*.conf' >> /etc/ld.so.conf
-    fi
-
     # We don't use a registry anymore, remove the old file
     rm -f /etc/ld.so.hwcappkgs
  
-    # /etc/ld.so.nohwcap code: NOHWCAP
-    # Handle upgrades when libc-opt package has been installed.
+    # /etc/ld.so.nohwcap code:
+        # Handle upgrades when libc-opt package has been installed.
     # When a /etc/ld.so.nohwcap file exists, ld.so only use libraries
     # from /lib, and ignore all optimised libraries. This file is
     # inconditionaly created in the preinst script of libc.
@@ -92,7 +73,7 @@ then
     # Get the list of optimized packages for a given architecture
     # Before removing a package from this list, make sure it appears
     # in the Conflicts: line of libc.
-    case $(dpkg --print-architecture) in
+    case ${DPKG_MAINTSCRIPT_ARCH} in
         alpha)
             hwcappkgs="libc6-alphaev67"
             ;;
@@ -102,12 +83,6 @@ then
         kfreebsd-i386)
             hwcappkgs="libc0.1-i686"
             ;;
-        mipsel)
-	    hwcappkgs="libc6-loongson2f"
-	    ;;
-        sparc)
-            hwcappkgs="libc6-sparcv9 libc6-sparcv9b"
-            ;;
     esac
  
     # We check the version between the current installed libc and
@@ -116,8 +91,8 @@ then
     all_upgraded=yes
     if [ -n "$hwcappkgs" ]; then
         for pkg in $hwcappkgs ; do
-            ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg\s\+//;s/\s.*//g")
-            if [ -n "$ver" ] && [ "$ver" != "2.13-38+deb7u10" ]; then
+            ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg[0-9a-z:]*\s\+//;s/\s.*//g")
+            if [ -n "$ver" ] && [ "$ver" != "2.24-10" ]; then
                 all_upgraded=no
             fi
         done
@@ -130,16 +105,14 @@ then
         rm -f /etc/ld.so.nohwcap
     fi
 
+
     # Load debconf module if available
     if [ -f /usr/share/debconf/confmodule ] ; then
 	. /usr/share/debconf/confmodule
     fi
 
-    if [ -n "$preversion" ]; then
-	if [ ! -d /var/mail ] && [ ! -L /var/mail ]; then
-	    ln -sf spool/mail /var/mail
-	fi
-	if dpkg --compare-versions "$preversion" lt 2.13; then
+    if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
+	if dpkg --compare-versions "$preversion" lt 2.24; then
 	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
 	    check="$check boa cucipop courier-authdaemon cron cups exim"
 	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
@@ -148,8 +121,8 @@ then
 	    check="$check sasl2-bin slapd smail sendmail snmpd ssh"
 	    check="$check spamassassin vsftpd wu-ftpd wu-ftpd-academ wwwoffle"
 	    check="$check webmin dropbear gdm"
-	    # NSS services check: NSS_CHECK
-	    echo -n "Checking for services that may need to be restarted..."
+	    # NSS services check: 
+	    	    echo -n "Checking for services that may need to be restarted..."
 	    # Only get the ones that are installed, and configured
 	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
 	    # some init scripts don't match the package names
@@ -185,6 +158,7 @@ then
 	    	    fi
 	    	fi
 	    done
+
 	    if [ -n "$services" ]; then
 
 	        if [ -f /usr/share/debconf/confmodule ] ; then
@@ -239,6 +213,13 @@ then
 		    echo "Restarting services possibly affected by the upgrade:"
 		    failed=""
 		    for service in $services; do
+			# We can't just use a generic rewrite here, as it was
+			# samba in wheezy and smbd in jessie, which confuses.
+			if [ "$service" = "samba" ]; then
+			    if [ -x /etc/init.d/smbd ] || [ -f /etc/init/smbd ]; then
+				service="smbd"
+			    fi
+			fi
 		    	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
 			    idl="invoke-rc.d ${service}"
 			elif [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
@@ -279,7 +260,7 @@ then
 			    echo
 			    echo "You will need to start these manually by running \`/etc/init.d/<service> start'"
 			    echo "If the service still fails to start, you may need to file a bug on"
-			    echo "$(package_name) or the service involved."
+			    echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
 			    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
 			    if [ "$frontend" != noninteractive ]; then
 			    	echo
@@ -299,19 +280,48 @@ then
 	    else
 		echo "Nothing to restart."
 	    fi
-	fi # end upgrading and $preversion lt 2.13
+	fi # end upgrading and $preversion lt 2.24
     fi # Upgrading
 
-    # Restart init. If it fails, there is nothing we can do, so 
-    # just ignore the error
-    telinit u 2> /dev/null || true ; sleep 1
+    # Restart init.  Currently handles chroots, systemd and upstart, and
+    # assumes anything else is going to not fail at behaving like
+    # sysvinit:
+    TELINIT=yes
+    if ischroot 2>/dev/null; then
+        # Don't bother trying to re-exec init from a chroot:
+        TELINIT=no
+    elif [ -d /run/systemd/system ]; then
+        # Skip if systemd is the active PID 1, since systemd doesn't
+        # need a reexec for a clean shutdown
+        TELINIT=no
+    elif [ -x "`which initctl`" ]; then
+        UPSTART=$(initctl version 2>/dev/null | awk '/upstart/ {print $3}' | tr -d ')')
+        if dpkg --compare-versions "$UPSTART" lt-nl 1.6.1; then
+            # This is an old upstart that can't re-exec statefully:
+            TELINIT=no
+            touch /var/run/init.upgraded
+        fi
+    fi
+    if [ "$TELINIT" = "yes" ]; then
+        telinit u 2>/dev/null || true ; sleep 1
+    fi
 fi
 
-# Automatically added by dh_makeshlibs
-if [ "$1" = "configure" ]; then
-	ldconfig
-fi
-# End automatically added section
+# We now use the multiarch triplet instead of the GNU triplet for the ld.so
+# configuration file, in order to keep a stable path. Remove the old file.
+case ${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)} in
+    hurd-i386)
+        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
+        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
+        ;;
+    i386)
+        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-linux-gnu.conf 2.19-4~ libc6:i386 -- "$@"
+        ;;
+    kfreebsd-i386)
+        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-kfreebsd-gnu.conf 2.19-11~ libc0.1:kfreebsd-i386 -- "$@"
+        ;;
+esac
+
 
 
 exit 0
